import 'package:hive/hive.dart';

part 'transaction_model.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0)
class TransactionModel {
  @HiveField(0)
  double amount;

  @HiveField(1)
  String type; // "Income" or "Expense"

  @HiveField(2)
  String category;

  @HiveField(3)
  DateTime date;

  @HiveField(4)
  String? notes;

  TransactionModel({
    required this.amount,
    required this.type,
    required this.category,
    required this.date,
    this.notes,
  });
}
